version : "3.8"

services:
  backend:
    build:
      context: ./agent
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - auth
    networks:
      - mynetwork
    env_file:
      - ./agent/.env
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - auth
      - backend
    networks:
      - mynetwork
    env_file:
      - ./frontend/.env
  auth:
    image: authimg
    ports:
      - "3000:3000"
    networks:
      - mynetwork
    env_file:
      - ./auth_server/.env

networks:
  mynetwork:
    driver: bridge