version : "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - auth
    networks:
      - mynetwork
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3001:80"
    depends_on:
      - backend
    networks:
      - mynetwork
  auth:
    build:
      context: .
      dockerfile: auth_server/Dockerfile
    ports:
      - "4000:4000"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge